import '@sl-design-system/button/register.js';
import '@sl-design-system/button-bar/register.js';
import '@sl-design-system/checkbox/register.js';
import '@sl-design-system/combobox/register.js';
import '@sl-design-system/date-field/register.js';
import '@sl-design-system/form/register.js';
import '@sl-design-system/listbox/register.js';
import '@sl-design-system/radio-group/register.js';
import '@sl-design-system/select/register.js';
import '@sl-design-system/switch/register.js';
import '@sl-design-system/text-area/register.js';
import '@sl-design-system/text-field/register.js';
import '@sl-design-system/time-field/register.js';
import { type StoryObj } from '@storybook/web-components-vite';
import { type TemplateResult } from 'lit';
import '../register.js';
import { type Form } from './form.js';
type Props = Pick<Form, 'disabled' | 'value'> & {
  buttons?(): TemplateResult;
  fields(args: Props): TemplateResult;
  reset: boolean;
  reportValidity?: boolean;
};
type Story = StoryObj<Props>;
declare const _default: {
  title: string;
  args: {
    disabled: false;
    reportValidity: false;
  };
  render: (args: Props) => TemplateResult<1>;
};
export default _default;
export declare const Basic: Story;
export declare const Autofocus: Story;
export declare const Reset: Story;
export declare const Array: Story;
export declare const DeepName: Story;
export declare const Disabled: Story;
export declare const Value: Story;
export declare const CustomComponent: Story;
export declare const All: Story;
export declare const AllDisabled: Story;
export declare const AllInvalid: Story;
export declare const AllValid: Story;
export declare const AsyncValidation: Story;
