compressionLevel: 0

enableColors: true

enableGlobalCache: true

nmMode: hardlinks-global

nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmRegistryServer: "https://npm.fontawesome.com/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
