approvedGitRepositories:
  - '**'

compressionLevel: 0

enableColors: true

enableGlobalCache: true

enableScripts: true

nmMode: hardlinks-global

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: '${FONT_AWESOME_AUTH_TOKEN}'
    npmRegistryServer: 'https://npm.fontawesome.com/'

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.17.0.cjs
