compressionLevel: 0

enableColors: true

enableGlobalCache: true

nmMode: hardlinks-global

nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: "${FONT_AWESOME_AUTH_TOKEN}"
    npmRegistryServer: "https://npm.fontawesome.com/"

yarnPath: .yarn/releases/yarn-4.1.0.cjs
