import { faMagnifyingGlass } from '@fortawesome/pro-regular-svg-icons';
import {
  type ScopedElementsMap,
  ScopedElementsMixin
} from '@open-wc/scoped-elements/lit-element.js';
import { Icon } from '@sl-design-system/icon';
import { SearchField, type SlSearchEvent } from '@sl-design-system/search-field';
import { type CSSResultGroup, LitElement, type TemplateResult, html, nothing } from 'lit';
import { query, state } from 'lit/decorators.js';
import MiniSearch, { type SearchResult } from 'minisearch';
import styles from './search.css' with { type: 'css' };

Icon.register(faMagnifyingGlass);

/** A single result as rendered in the listbox. */
interface SearchResultItem {
  title: string;
  description: string;
  url: string;
  /** Icon name (e.g. `far-bolt`) inherited from the page's category. */
  icon: string;
}

/** The shape of the `search.json` file generated by the Eleventy search plugin. */
interface SearchData {
  searchIndex: unknown;
  map: SearchResultItem[];
}

/** The fields the index is built with; must match the Eleventy search plugin. */
const SEARCH_FIELDS = ['t', 'h', 'c'];

export class Search extends ScopedElementsMixin(LitElement) {
  /** @internal */
  static get scopedElements(): ScopedElementsMap {
    return {
      'sl-icon': Icon,
      'sl-search-field': SearchField
    };
  }

  /** @internal */
  static styles: CSSResultGroup = styles;

  /** The MiniSearch index, loaded lazily the first time the dialog is opened. */
  #index?: MiniSearch;

  /** Maps a result id to its display data (title, description, url). */
  #map: SearchResultItem[] = [];

  /** Tracks the in-flight or completed load of the search index. */
  #loadPromise?: Promise<void>;

  #onKeydown = (event: KeyboardEvent): void => {
    if (event.key === 'k' && (event.metaKey || event.ctrlKey)) {
      event.preventDefault();
      this.#open();
    }
  };

  @query('dialog') dialog?: HTMLDialogElement;

  /** Index of the currently highlighted result, or -1 if none. */
  @state() activeIndex = -1;

  /** The current query string. */
  @state() query = '';

  /** The current result list. */
  @state() results: SearchResultItem[] = [];

  /** Whether the index is still being loaded. */
  @state() loading = false;

  override connectedCallback(): void {
    super.connectedCallback();

    document.addEventListener('keydown', this.#onKeydown);
  }

  override disconnectedCallback(): void {
    document.removeEventListener('keydown', this.#onKeydown);

    super.disconnectedCallback();
  }

  render(): TemplateResult {
    const isMac = navigator.platform.includes('Mac');

    return html`
      <button @click=${this.#open} type="button">
        <sl-icon name="far-magnifying-glass"></sl-icon>
        <span>Search</span>
        <kbd>${isMac ? '⌘' : 'Ctrl+'}K</kbd>
      </button>

      <dialog
        @click=${this.#onBackdropClick}
        @keydown=${this.#onDialogKeydown}
        aria-label="Search documentation">
        <div class="container">
          <!-- eslint-disable-next-line lit-a11y/aria-activedescendant-has-tabindex -->
          <sl-search-field
            @sl-search=${this.#onSearch}
            aria-label="Search documentation"
            aria-activedescendant=${this.activeIndex >= 0 ? `result-${this.activeIndex}` : nothing}
            aria-controls="search-results"
            placeholder="Search documentation..."
            role="combobox"
            aria-expanded="true"
            aria-autocomplete="list"></sl-search-field>

          ${this.#renderResults()}
        </div>
      </dialog>
    `;
  }

  #renderResults(): TemplateResult {
    if (this.loading) {
      return html`<p class="message">Loading search index…</p>`;
    }

    if (!this.query) {
      return html`<p class="message">Start typing to search the documentation.</p>`;
    }

    if (this.results.length === 0) {
      return html`<p class="message">No results found for “${this.query}”.</p>`;
    }

    return html`
      <ul class="results" role="listbox" id="search-results" aria-label="Search results">
        ${this.results.map(
          (result, index) => html`
            <li
              id="result-${index}"
              role="option"
              class=${index === this.activeIndex ? 'active' : nothing}
              aria-selected=${index === this.activeIndex || nothing}
              @click=${() => this.#select(index)}>
              <sl-icon name=${result.icon || 'far-file-lines'}></sl-icon>
              <div class="result-content">
                <span class="result-title">${result.title}</span>
                ${result.description
                  ? html`<span class="result-description">${result.description}</span>`
                  : nothing}
                <span class="result-path">${result.url.replace(/^\//, '')}</span>
              </div>
            </li>
          `
        )}
      </ul>
    `;
  }

  #open(): void {
    this.dialog?.showModal();
    this.activeIndex = -1;

    void this.#loadIndex();

    requestAnimationFrame(() => {
      this.renderRoot.querySelector<HTMLElement>('sl-search-field')?.focus();
    });
  }

  /** Lazily fetches and parses the search index, building the MiniSearch instance once. */
  async #loadIndex(): Promise<void> {
    if (this.#index || this.#loadPromise) {
      return this.#loadPromise;
    }

    this.loading = true;

    this.#loadPromise = (async () => {
      try {
        const response = await fetch('/search.json'),
          data = (await response.json()) as SearchData;

        this.#index = MiniSearch.loadJSON(JSON.stringify(data.searchIndex), {
          fields: SEARCH_FIELDS
        });
        this.#map = data.map;
      } catch {
        // Leave the index undefined; searches will simply return no results.
      } finally {
        this.loading = false;
      }
    })();

    return this.#loadPromise;
  }

  #onSearch(event: SlSearchEvent): void {
    this.#search(event.detail);
  }

  #search(query: string): void {
    this.query = query.trim();

    if (!this.query || !this.#index) {
      this.results = [];
      this.activeIndex = -1;
      return;
    }

    const matches = this.#index.search(this.query, {
      prefix: true,
      fuzzy: 0.2,
      boost: { t: 20, h: 10, c: 1 }
    });

    // Re-rank so that title matches win: MiniSearch's score doesn't account for
    // where in the title a term matches, so boost exact/prefix/word-boundary title hits.
    const queryLower = this.query.toLowerCase(),
      rankTitle = (title: string): number => {
        if (title === queryLower) {
          return 3;
        } else if (title.startsWith(queryLower)) {
          return 2;
        } else if (
          new RegExp(`\\b${queryLower.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`).test(title)
        ) {
          return 1;
        } else {
          return 0;
        }
      };

    matches.sort((a: SearchResult, b: SearchResult) => {
      const rankDiff =
        rankTitle((this.#map[b.id]?.title ?? '').toLowerCase()) -
        rankTitle((this.#map[a.id]?.title ?? '').toLowerCase());

      return rankDiff !== 0 ? rankDiff : b.score - a.score;
    });

    this.results = matches
      .map(match => this.#map[match.id])
      .filter((page): page is SearchResultItem => !!page?.url);

    // Highlight the first result so Enter navigates to the top match.
    this.activeIndex = this.results.length > 0 ? 0 : -1;
  }

  #select(index: number): void {
    const result = this.results[index];
    if (!result) {
      return;
    }

    this.dialog?.close();
    window.location.href = result.url;
  }

  #onBackdropClick(event: MouseEvent): void {
    const dialog = this.dialog;

    if (!dialog || dialog !== event.composedPath()[0]) {
      return;
    }

    const rect = dialog.getBoundingClientRect();

    if (
      event.clientY < rect.top ||
      event.clientY > rect.bottom ||
      event.clientX < rect.left ||
      event.clientX > rect.right
    ) {
      dialog.close();
    }
  }

  #onDialogKeydown(event: KeyboardEvent): void {
    if (event.key === 'Escape') {
      event.preventDefault();
      this.dialog?.close();
      return;
    }

    if (this.results.length === 0) {
      return;
    }

    if (event.key === 'ArrowDown') {
      event.preventDefault();
      this.activeIndex = this.activeIndex < this.results.length - 1 ? this.activeIndex + 1 : 0;
      this.#scrollActiveIntoView();
    } else if (event.key === 'ArrowUp') {
      event.preventDefault();
      this.activeIndex = this.activeIndex > 0 ? this.activeIndex - 1 : this.results.length - 1;
      this.#scrollActiveIntoView();
    } else if (event.key === 'Enter' && this.activeIndex >= 0) {
      event.preventDefault();
      this.#select(this.activeIndex);
    }
  }

  #scrollActiveIntoView(): void {
    this.renderRoot
      .querySelectorAll('.results li')
      [this.activeIndex]?.scrollIntoView({ block: 'nearest' });
  }
}
