name: 📚 Documentation
description: Have an issue or improvement for the SL Design System documentation?
labels: ["documentation", "triage"]
projects: ["projects/2"]
body:
  - type: markdown
    attributes:
      value: "### Thanks for filing an issue! Before you submit, search open/closed issues before submitting since someone might have asked the same thing before!"
  - type: markdown
    attributes:
      value: "# 📚 Documentation"
  - type: textarea
    id: general-summary
    attributes:
      label: Provide a general summary of the documentation request here
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## 🦄 Other"
  - type: input
    id: company-team
    attributes:
      label: 🧢 Your Product/Team
      description: Which product team is requesting this change? (i.e. Bingel DC/Pokemon)
