name: 🧩 New component
description: Outline the requirements for a new component
labels: [request, triage]
projects: ["projects/2"]
body:
    - type: markdown
      attributes:
          value: "### Thanks for filing an issue! Before you submit, search open/closed issues before submitting since someone might have asked the same thing before!"
    - type: markdown
      attributes:
          value: "# 🧩 New component"
    - type: input
      id: component-name
      attributes:
          label: ✒️ Name of component
      validations:
          required: true
    - type: textarea
      id: specs
      attributes:
          label: 👩‍🎨 Design specification
          description: Snapshots and link to mock-ups for this component and structure
    - type: textarea
      id: interaction
      attributes:
          label: 🖱️ Interaction
          description: General guidance for how a user should interact with this component
    - type: textarea
      id: a11y
      attributes:
          label: 🚪 Accessibility
          description: Guidance for keyboard navigation and screen-reader engagement
    - type: textarea
      id: other
      attributes:
          label: 📋 Other requirements
    - type: markdown
      attributes:
          value: "## 🦄 Other"
    - type: input
      id: name
      attributes:
          label: 👤 Your name
          description: Please provide your full name
      validations:
          required: true
    - type: input
      id: product
      attributes:
          label: 🧢 Your Product/Team
          description: Which product team needs this component? (i.e. Bingel DC/Pokemon)
