name: 🐛 Bug Report
description: File a bug report
title: '[Bug]: '
labels: [bug, triage]
projects: "components/2"
body:
  - type: markdown
    attributes:
      value: "### Thanks for filing an issue! Before you submit, search open/closed issues before submitting since someone might have asked the same thing before!"
  - type: markdown
    attributes:
      value: "# 🐛 Bug Report "
  - type: textarea
    id: general-summary
    attributes:
      label: Provide a general summary of the issue here
    validations:
      required: true
  - type: checkboxes
    id: where
    attributes:
      label: 🕵️‍♀️ Where does this bug appear?
      options:
      - label: Storybook
      - label: Figma Toolkit
      - label: My own environment
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 🤔 Expected Behavior?
      description: Tell us what should happen
    validations:
      required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: 😯 Current Behavior
      description: | 
        Tell us what happens instead of the expected behavior.
    validations:
      required: true
  - type: textarea
    id: possible-solution
    attributes:
      label: 💁 Possible Solution
      description: Suggest a fix/reason for the bug
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: 📷 Screenshots
      description: | 
        You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: textarea
    id: base-reproduction
    attributes:
      label: 🖥️ Steps to Reproduce 
      description: | 
        Provide a minimal test case that can reproduce the problem.
      value: |
              1. Go to '...'
              2. Click on '....'
              3. Scroll to '....'
              4. Check console
              5. See error
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## 🌍 Your Environment"
  - type: input
    id: version
    attributes:
      label: Version (only for bugs in code)
      description: What version of sl-design-system are you running?
  - type: dropdown 
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on? (only for bugs in code)
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
  - type: input
    id: other
    attributes:
      label: If other, please specify.
  - type: input
    id: operating-system
    attributes:
      label: What operating system are you using? (only for bugs in code)
  - type: markdown
    attributes:
      value: "## 🦄 Other"
  - type: input
    id: product
    attributes:
      label: 🧢 Your product/team
      description: | 
        Which product team is this bug impacting? (i.e. Bingel DC/Pokemon)
    validations:
      required: false
  - type: dropdown
    id: theme
    attributes:
      label: 🎨 Your Theme(s)
      description: Which theme(s) do you use?
      multiple: true
      options:
      - Bingel DC
      - Bingel INT
      - Editorial Suite
      - ItsLearning
      - Kampus
      - Magister
      - Max Online
      - My Digital Book
      - My Van in
      - NEON
      - Sanoma Learning
      - Sanoma Utbildning
      - TEAS
    validations:
      required: true
