name: 🙋 Feature Request
description: Want to add a feature to SL Design System?
labels: ["enhancement", "development", "triage"]
projects: ["projects/2"]
body:
  - type: markdown
    attributes:
      value: "### Thanks for filing an issue! Before you submit, search open/closed issues before submitting since someone might have asked the same thing before!"
  - type: markdown
    attributes:
      value: "# 🙋 Feature Request "
  - type: textarea
    id: general-summary
    attributes:
      label: Provide a general summary of the feature here
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 🤔 Expected Behavior?
      description: Tell us how the feature should work!
    validations:
      required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: 😯 Current Behavior
      description: | 
        Explain the difference from current behavior
    validations:
      required: true
  - type: textarea
    id: possible-solution
    attributes:
      label: 💁 Possible Solution
      description: Ideas how to implement this feature or a similar solution/workaround that already exists
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: 📷 Screenshots
      description: | 
        You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
    - type: textarea
    id: context
    attributes:
      label: 🔦 Context 
      description: | 
        Providing context helps us come up with a solution that is most useful in the real world. How has this issue affected you? What are you trying to accomplish?
    validations:
      required: true
    - type: textarea
    id: base-reproduction
    attributes:
      label: 🖥️ Examples 
      description: | 
        Examples help us understand the requested feature better. Include design mocks here if possible.
    validations:
      required: false
  - type: markdown
    attributes:
      value: "## 🦄 Other"
  - type: input
    id: product
    attributes:
      label: 🧢 Your product/team
      description: | 
        Which product team needs this feature? (i.e. Bingel DC/Pokemon)
    validations:
      required: true
