name: General
description: Create a general issue to improve the project
labels: [triage]
# assignees:
body:
    - type: markdown
      attributes:
          value: Thanks for taking the time to fill out this issue!
    - type: textarea
      id: issue-details
      attributes:
          label: Description of issue
          description: Please tell us about the issue. You can attach images or files by clicking this area to highlight it and then dragging files in.
