name: Clean

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  FONT_AWESOME_AUTH_TOKEN: ${{ secrets.FONT_AWESOME_AUTH_TOKEN }}
  HUSKY: 0

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# permissions:
#   contents: read
#   pages: write
#   pull-requests: write
#   id-token: write

jobs:
  cleanWireit:
    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - run: find **/.wireit

      - run: rm -rf **/.wireit
