name: Tokens

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'packages/tokens/src/**'

env:
  FIGMA_TOKEN: ${{ secrets.FIGMA_AUTH_TOKEN }}
  FONT_AWESOME_AUTH_TOKEN: ${{ secrets.FONT_AWESOME_AUTH_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn transform-tokens
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '⚙️ Generate theme tokens'
